//////////////////////////////////////////////////////////////////////
// Attribute
//////////////////////////////////////////////////////////////////////

//ドキュメント種類
:doctype: book
//ドキュメント言語
:lang: ja
//目次生成
:toc: left
//目次生成階層数
:toclevels: 2
//目次タイトル
:toc-title: 目次
//章番号生成
:sectnums:
//章番号生成階層数
:sectlevels: 
//PDF化時の章タイトル
:chapter-label:
//シンタックスハイライト
:source-highlighter: coderay
//アイコンフォント
:icons: font
//UIマクロ
:experimental:
//HTML化時の画像のdata-uri要素化
:data-uri:
//画像ファイル格納先
:imagesdir: ./images
//HTML化時のスタイルファイル格納先
:stylesdir: ./style
//HTML化時のスタイルファイル
:stylesheet: asciidoctor-default.css
//PDF化時のスタイルファイル
:pdf-style: ./style/public_style.yml
//PDF化時のフォントファイル格納先
:pdf-fontsdir: ./fonts

//////////////////////////////////////////////////////////////////////
// 表紙
//////////////////////////////////////////////////////////////////////

//ドキュメントタイトル、表紙に入る
= メリット
//ドキュメントタイトル、ヘッダーに入る
:docname: メリット
//著者
:author:
//改定番号
:revnumber: K0.1
//改定日
:revdate: 2019/08/24
//改定番号のラベル
:version-label:
//ロゴ画像
//:title-logo-image:
//表紙背景画像 
//:title-page-background-image:

//////////////////////////////////////////////////////////////////////
// 本文
//////////////////////////////////////////////////////////////////////





Soft:コミットメッセージだけ修正してコミットし直したい
Mixed:変更内容を追加してコミットし直したい
Hard:コミット自体なかったことにしたい



ブランチはどんな時に使うか

* 大きな修正や追加を加えたいがちゃんとできるか心配
* ちょこちょこ直しがあって安定バージョンをわかりやすくとっておきたい

ブランチを切ってそちらで作業を進めることでmasterを安定バージョンとして管理


Gitにとってコミットとはパッチ作成であり、マージとはたまったパッチをまとめて適用する作業である

pull-request(marge-request)
こんな素晴らしい変更をしたからレビューしてOKだったら取り込んでねと依頼する機能
これには暗黙のルールがあって最新をベースに変更したものをpull-requestしないといけません
たとえ、古いものをベースに変更したものをpull-requestしてもレビュアに最新にrebaseしてねと言われるだけ
こうして中央リポジトリにはレビューされたものだけが本流へマージされていくことになる
gitはブランチとpull-requestの機能をうまく適用してこそのもの

* gitで差分管理できる
* gitサービス上でコメントとかissueを付けられる
* メンバ間でドキュメントのクオリティ差があまりでない

asciidoc自体の記法が少ないことで良い意味で制限がかかりメンバ間でフォーマットに統一感が出てくる

セールス、サポート、ソースコードなど担当や領域ごとにリポジトリ（ファイル保管場所）を設け、各リポジトリの中にそのチームのメンバがタスクを格納していく

タスクの登録はissuseというタスク管理機能を使います
各タスクをissueとしてスレッドを立て進捗状況を記していく

issueごとに関係者をアサインすることができ、官僚するなど動きがあれば彼らに通知が届く
進捗確認や打ち合わせが不要になるためコミュニケーションコストはかなり削減される

例えば、officeのファイルだと、最新版を格納するプロダクトごとのフォルダ、自前PCに保存するローカルのプロダクトごとのフォルダ、バックアップのためのフォルダ、それぞれを更新かけないといけない
またほかのプロダクトにも水平展開したい標準化の仕様を一元管理できる


ドキュメント作成の課題
https://garbagetown.github.io/jjug-ccc-2017-fall/#8


これらの画像の1つを生成するのは非常に簡単ですが、ドキュメントに多くの図を追加し始めると、処理時間が長くなります。Asciidoctor Diagramは、*。cacheファイル内のダイアグラムのメタデータを追跡することで処理を最適化し、ダイアグラムのソースコードが変更された場合にのみ画像を再生成します。これにより、ドキュメントのインクリメンタルレンダリングが迅速に処理されます。

メタデータとは、主となるデータの説明書きが書いてあるデータのこと
データの中身＋付帯情報＝データ、で付帯情報のこと
ざっくりいうと、自己紹介カードみたいなの
ほかのいいかたをするとofiiceの作成者・作成日・サイズとかのこと
https://wa3.i-3-i.info/word15688.html


ドットではじまるファイル・フォルダは隠しファイル？システムが使用するフォルダのことなので気にしない、ただし、gitで管理するときは不要なファイルになるので、gitignoreに事前に登録しておく（git上でplantumlを表示するのに必要？）
https://qiita.com/sgur/items/745e0ee02c69b50bf9e5
https://qiita.com/masakura/items/d8c7563f2f6744819c7a#plantuml--gitlab
https://docs.gitlab.com/ce/administration/integration/plantuml.html　→　宮森さんに依頼

asciidocの記法　簡潔ですばらしい
http://etc9.hatenablog.com/entry/2015/02/13/002421

































